src/objects/Funding_Program__c.object
<CustomObject>
    <label>Funding Program</label>
    <nameField>
        <label>Funding Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Period__c.object
<CustomObject>
    <description>Represents a funding or reporting period for a Funding Program</description>
    <label>Program Period</label>
    <nameField>
        <displayFormat>PP - {00000}</displayFormat>
        <label>Program Period ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Funding_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Reporting Periods must be related to a Funding Period</inlineHelpText>
        <label>Funding Period</label>
        <referenceTo>Program_Period__c</referenceTo>
        <relationshipLabel>Reporting Periods</relationshipLabel>
        <relationshipName>Program_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funding_Program__c</fullName>
        <label>Funding Program</label>
        <referenceTo>Funding_Program__c</referenceTo>
        <relationshipLabel>Program Periods</relationshipLabel>
        <relationshipName>Program_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Period_End_Date__c</fullName>
        <label>Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Total_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Period Total Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period_Total_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Period Total Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Period_Type__c</fullName>
        <label>Period Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Funding</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/ReportingPeriodRollupCalculationTest.cls
@isTest
private class ReportingPeriodRollupCalculationTest {

    @TestSetup
    static void makeData() {
        Funding_Program__c fundingProgram = new Funding_Program__c(
            Name = 'Test Program'
        );
        insert fundingProgram;

        Program_Period__c period = new Program_Period__c(
            Period_Type__c = 'Funding',
            Funding_Program__c = fundingProgram.Id,
            Period_End_Date__c = Date.today().addMonths(2)
        );
        insert period;

        maica_cc__Support_Category__c supportCategory = new maica_cc__Support_Category__c(
            maica_cc__NDIS_Name__c = 'CONSUMABLES'
        );
        insert supportCategory;

        maica_cc__Support_Item__c supportItem = new maica_cc__Support_Item__c(
            Name = 'Support Item',
            maica_cc__Support_Item_Number__c = '1234',
            maica_cc__Support_Category__c = supportCategory.Id
        );
        insert supportItem;

        List<Program_Period__c> programPeriods = new List<Program_Period__c>{
            new Program_Period__c(
                Period_Total_Quantity__c = 3,
                Period_Total_Value__c = 4,
                Funding_Program__c = fundingProgram.Id,
                Funding_Period__c = period.Id
            ),
            new Program_Period__c(
                Period_Total_Quantity__c = 5,
                Period_Total_Value__c = 6,
                Funding_Program__c = fundingProgram.Id,
                Funding_Period__c = period.Id
            )
        };
        insert programPeriods;
    }

    @isTest
    static void testBehavior() {
        Test.startTest();
        Database.executeBatch(new ReportingPeriodRollupCalculationBatch());
        Test.stopTest();

        Program_Period__c updatedPeriod = [
            SELECT Period_Total_Quantity__c, Period_Total_Value__c
            FROM Program_Period__c
            WHERE Period_Type__c = 'Funding'
            LIMIT 1
        ];

        // Zeroing occurs in FLow
        Assert.areEqual(0, updatedPeriod.Period_Total_Quantity__c, 'Invalid Period Total Quantity amount');
        Assert.areEqual(0, updatedPeriod.Period_Total_Value__c, 'Invalid Period Total Value amount');
    }
}