src/objects/Program_Period__c.object
<CustomObject>
    <description>Represents a funding or reporting period for a Funding Program</description>
    <label>Program Period</label>
    <nameField>
        <displayFormat>PP - {00000}</displayFormat>
        <label>Program Period ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Funding_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Reporting Periods must be related to a Funding Period</inlineHelpText>
        <label>Funding Period</label>
        <referenceTo>Program_Period__c</referenceTo>
        <relationshipLabel>Reporting Periods</relationshipLabel>
        <relationshipName>Program_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period_Total_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Period Total Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period_Total_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Period Total Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Period_Type__c</fullName>
        <label>Period Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Funding</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/ReportingPeriodRollupCalculationProc.cls
public with sharing class ReportingPeriodRollupCalculationProc extends AbstractProcessor {

    public override Response process(Request request) {
        this.request = request;
        this.doSubmit();
        return this.response;
    }

    private void doSubmit() {
        String periodId = this.request.getRequiredString('periodId');

        Program_Period__c programPeriod = (Program_Period__c) Utils.arrays.firstOrException(
            [SELECT Id FROM Program_Period__c WHERE Id = :periodId],
            'No Funding Program_Period__c with Id: ' + periodId
        );

        List<Program_Period__c> programPeriods = [
            SELECT Id, Period_Total_Quantity__c, Period_Total_Value__c
            FROM Program_Period__c
            WHERE Funding_Period__c = :periodId
            AND Period_Type__c != 'Reporting'
        ];

        Decimal periodTotalQuantity = 0;
        Decimal periodTotalValue = 0;

        for (Program_Period__c programPeriodItem : programPeriods) {
            periodTotalQuantity += Utils.objects.defaultIfNull(programPeriodItem.Period_Total_Quantity__c, 0);
            periodTotalValue += Utils.objects.defaultIfNull(programPeriodItem.Period_Total_Value__c, 0);
        }

        programPeriod.Period_Total_Quantity__c = periodTotalQuantity;
        programPeriod.Period_Total_Value__c = periodTotalValue;
        update programPeriod;
    }
}