src/objects/Program_Period__c.object
<CustomObject>
    <description>Represents a funding or reporting period for a Funding Program</description>
    <label>Program Period</label>
    <nameField>
        <displayFormat>PP - {00000}</displayFormat>
        <label>Program Period ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Period_End_Date__c</fullName>
        <label>Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Type__c</fullName>
        <label>Period Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Funding</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/ReportingPeriodRollupCalculationBatch.cls
public with sharing class ReportingPeriodRollupCalculationBatch implements Database.Batchable<SObject>, Schedulable {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        Date todayPlusMonth = Date.today().addMonths(1);

        return Database.getQueryLocator(
            'SELECT Id FROM Program_Period__c ' +
            'WHERE Period_Type__c = \'Funding\' ' +
            'AND Period_End_Date__c > :todayPlusMonth'
        );
    }

    public void execute(Database.BatchableContext bc, List<SObject> records) {
        for (SObject record : records) {
            Response response = new ReportingPeriodRollupCalculationProc().process(
                new Map<String, Object>{
                    'periodId' => record.Id
                }
            );
        }
    }

    public void finish(Database.BatchableContext bc) {}

    public void execute(SchedulableContext param) {
        Database.executeBatch(new InvoiceLineItemRollupCalculationBatch(), 1);
    }
}